apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubebench.svcName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubebench.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "kubebench.selectorLabels" . | nindent 4 }}