{
 "title": "Kubebench",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "data source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kubebench_total{job=\"$job\"}, namespace)"
    }
   },
   { "name": "job", "label": "job", "query": "kubeblocks-service,agamotto" },
   {
    "name": "benchmark",
    "label": "benchmark",
    "query": {
     "query": "label_values(kubebench_total{job=\"$job\"}, benchmark)"
    }
   },
   {
    "name": "name",
    "label": "name",
    "query": {
     "query": "label_values(kubebench_total{job=\"$job\", benchmark=\"$benchmark\"}, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pgbench",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scale",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by(name) (kubebench_pgbench_scale{namespace=~\"$namespace\", name=\"$name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Clients",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by(name) (kubebench_pgbench_clients{namespace=~\"$namespace\", name=\"$name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by(name) (kubebench_pgbench_threads{namespace=~\"$namespace\", name=\"$name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TransactionsProcessed",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by(name) (kubebench_pgbench_transactions_processed{namespace=~\"$namespace\", name=\"$name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TransactionsFailed",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by(name) (kubebench_pgbench_transactions_failed{namespace=~\"$namespace\", name=\"$name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TransactionsPerClient",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by(name) (kubebench_pgbench_transactions_per_client{namespace=~\"$namespace\", name=\"$name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "StdLatency",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by(name) (kubebench_pgbench_std_latency{namespace=~\"$namespace\", name=\"$name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "AvgLatency",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by(name) (kubebench_pgbench_avg_latency{namespace=~\"$namespace\", name=\"$name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "InitialConnectionTime",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by(name) (kubebench_pgbench_initial_connections_time{namespace=~\"$namespace\", name=\"$name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TPS",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by(name) (kubebench_pgbench_tps{namespace=~\"$namespace\", name=\"$name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "MaximumTry",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by(name) (kubebench_pgbench_maximum_try{namespace=~\"$namespace\", name=\"$name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TPS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "kubebench_pgbench_tps_second{namespace=~\"$namespace\", name=\"$name\"}",
       "legendFormat": "{{namespace}} | {{benchmark}} | {{name}}"
      }
     ]
    },
    {
     "title": "TransactionFailed",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "kubebench_pgbench_transactions_failed_second{namespace=~\"$namespace\", name=\"$name\"}",
       "legendFormat": "{{namespace}} | {{benchmark}} | {{name}}"
      }
     ]
    },
    {
     "title": "AvgLatency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "kubebench_pgbench_avg_latency_second{namespace=~\"$namespace\", name=\"$name\"}",
       "legendFormat": "{{namespace}} | {{benchmark}} | {{name}}"
      }
     ]
    },
    {
     "title": "StdLatency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "kubebench_pgbench_std_latency_second{namespace=~\"$namespace\", name=\"$name\"}",
       "legendFormat": "{{namespace}} | {{benchmark}} | {{name}}"
      }
     ]
    }
   ]
  },
  { "title": "Sysbench", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Threads",
   "type": "stat",
   "description": "the thread number",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(name) (kubebench_sysbench_threads{name=\"$name\", namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "stat",
   "description": "the duration of test",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(name) (kubebench_sysbench_total_time{name=\"$name\", namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Thread Lifetime",
   "type": "stat",
   "description": "The average thread lifetime.",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(name) (kubebench_sysbench_exec_time_avg{name=\"$name\", namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stddev Thread Lifetime",
   "type": "stat",
   "description": "The standard deviation of thread lifetime",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(name) (kubebench_sysbench_exec_time_stddev{name=\"$name\", namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TotalEvents",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(name) (kubebench_sysbench_total_events{name=\"$name\", namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Thread Events",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(name) (kubebench_sysbench_events_avg{name=\"$name\", namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stddev Thread Events",
   "type": "stat",
   "description": "the standard deviation of thread events",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(name) (kubebench_sysbench_events_stddev{name=\"$name\", namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(name) (kubebench_sysbench_transactions{name=\"$name\", namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(name) (kubebench_sysbench_query_total{name=\"$name\", namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read Queries",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(name) (kubebench_sysbench_query_read{name=\"$name\", namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write Queries",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(name) (kubebench_sysbench_query_write{name=\"$name\", namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Other Queries",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(name) (kubebench_sysbench_query_other{name=\"$name\", namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SumLatency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(name) (kubebench_sysbench_latency_sum{name=\"$name\", namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MinLatency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(name) (kubebench_sysbench_latency_min{name=\"$name\", namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MaxLatency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(name) (kubebench_sysbench_latency_max{name=\"$name\", namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AvgLatency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(name) (kubebench_sysbench_latency_avg{name=\"$name\", namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "99th Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(name) (kubebench_sysbench_latency_ninety_ninth{name=\"$name\", namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IgnoredErrors",
   "type": "stat",
   "description": "the total of ignore errors",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(name) (kubebench_sysbench_ignored_errors{name=\"$name\", namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reconnects",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(name) (kubebench_sysbench_reconnects{name=\"$name\", namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "kubebench_sysbench_tps_second{name=\"$name\", namespace=~\"$namespace\"}",
     "legendFormat": "{{namespace}} | {{benchmark}} | {{name}}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "kubebench_sysbench_qps_second{name=\"$name\", namespace=~\"$namespace\"}",
     "legendFormat": "{{namespace}} | {{benchmark}} | {{name}}"
    }
   ]
  },
  {
   "title": "Read QPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "kubebench_sysbench_read_qps_second{name=\"$name\", namespace=~\"$namespace\"}",
     "legendFormat": "{{namespace}} | {{benchmark}} | {{name}}"
    }
   ]
  },
  {
   "title": "Write QPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "kubebench_sysbench_write_qps_second{name=\"$name\", namespace=~\"$namespace\"}",
     "legendFormat": "{{namespace}} | {{benchmark}} | {{name}}"
    }
   ]
  },
  {
   "title": "Other QPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "kubebench_sysbench_other_qps_second{name=\"$name\", namespace=~\"$namespace\"}",
     "legendFormat": "{{namespace}} | {{benchmark}} | {{name}}"
    }
   ]
  },
  {
   "title": "IgnoreErrs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "kubebench_sysbench_errors_second{name=\"$name\", namespace=~\"$namespace\"}",
     "legendFormat": "{{namespace}} | {{benchmark}} | {{name}}"
    }
   ]
  },
  {
   "title": "99th Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "kubebench_sysbench_latency_second{name=\"$name\", namespace=~\"$namespace\"}",
     "legendFormat": "{{namespace}} | {{benchmark}} | {{name}}"
    }
   ]
  },
  {
   "title": "Reconnects",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "kubebench_sysbench_reconnects_second{name=\"$name\", namespace=~\"$namespace\"}",
     "legendFormat": "{{namespace}} | {{benchmark}} | {{name}}"
    }
   ]
  }
 ]
}