# permissions for end users to view redisbenches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: redisbench-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubebench
    app.kubernetes.io/part-of: kubebench
    app.kubernetes.io/managed-by: kustomize
  name: redisbench-viewer-role
rules:
- apiGroups:
  - benchmark.apecloud.io
  resources:
  - redisbenches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - benchmark.apecloud.io
  resources:
  - redisbenches/status
  verbs:
  - get
