---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - benchmark.kubebench.io
  resources:
  - sysbenches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - benchmark.kubebench.io
  resources:
  - sysbenches/finalizers
  verbs:
  - update
- apiGroups:
  - benchmark.kubebench.io
  resources:
  - sysbenches/status
  verbs:
  - get
  - patch
  - update
