apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubebench.fullname" . }}-proxy-rolebinding
  labels:
    {{- include "kubebench.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubebench.fullname" .}}-proxy-role
subjects:
- kind: ServiceAccount
  name: {{ include "kubebench.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
