---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubebench.fullname" . }}-manager-role
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - benchmark.apecloud.io
  resources:
  - fios
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - benchmark.apecloud.io
  resources:
  - fios/finalizers
  verbs:
  - update
- apiGroups:
  - benchmark.apecloud.io
  resources:
  - fios/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - benchmark.apecloud.io
  resources:
  - pgbenches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - benchmark.apecloud.io
  resources:
  - pgbenches/finalizers
  verbs:
  - update
- apiGroups:
  - benchmark.apecloud.io
  resources:
  - pgbenches/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - benchmark.apecloud.io
  resources:
  - redisbenches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - benchmark.apecloud.io
  resources:
  - redisbenches/finalizers
  verbs:
  - update
- apiGroups:
  - benchmark.apecloud.io
  resources:
  - redisbenches/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - benchmark.apecloud.io
  resources:
  - sysbenches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - benchmark.apecloud.io
  resources:
  - sysbenches/finalizers
  verbs:
  - update
- apiGroups:
  - benchmark.apecloud.io
  resources:
  - sysbenches/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - benchmark.apecloud.io
  resources:
  - tpccs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - benchmark.apecloud.io
  resources:
  - tpccs/finalizers
  verbs:
  - update
- apiGroups:
  - benchmark.apecloud.io
  resources:
  - tpccs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - benchmark.apecloud.io
  resources:
  - tpches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - benchmark.apecloud.io
  resources:
  - tpches/finalizers
  verbs:
  - update
- apiGroups:
  - benchmark.apecloud.io
  resources:
  - tpches/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - benchmark.apecloud.io
  resources:
  - ycsbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - benchmark.apecloud.io
  resources:
  - ycsbs/finalizers
  verbs:
  - update
- apiGroups:
  - benchmark.apecloud.io
  resources:
  - ycsbs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - deletecollection
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
  - list
