apiVersion: benchmark.apecloud.io/v1alpha1
kind: Pgbench
metadata:
  labels:
    app.kubernetes.io/name: pgbench
    app.kubernetes.io/instance: pgbench-sample
    app.kubernetes.io/part-of: kubebench
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubebench
  name: pgbench-sample
spec:
  scale: 10
  clients:
    - 2
    - 4
  threads: 2
    #transactions: 30000
  duration: 60
  mode: run
  target:
    host: "test-pg-postgresql.default.svc.cluster.local"
    port: 5432
    user: "postgres"
    password: "xxx"
    database: "postgres"