apiVersion: benchmark.apecloud.io/v1alpha1
kind: Redisbench
metadata:
  labels:
    app.kubernetes.io/name: redisbench
    app.kubernetes.io/instance: redisbench-sample
    app.kubernetes.io/part-of: kubebench
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubebench
  name: redisbench-sample
spec:
  # TODO(user): Add fields here
