apiVersion: benchmark.apecloud.io/v1alpha1
kind: Redisbench
metadata:
  labels:
    app.kubernetes.io/name: redisbench
    app.kubernetes.io/instance: redisbench-sample
    app.kubernetes.io/part-of: kubebench
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubebench
  name: redisbench-sample
spec:
  clients:
    - 2
    - 4
  requests: 100000
  dataSizes: 3
  pipeline: 16
  target:
    host: "test-redis-redis.default.svc.cluster.local"
    port: 6379
    user: "xxx"
    password: "xxx"
