apiVersion: benchmark.apecloud.io/v1alpha1
kind: Ycsb
metadata:
  labels:
    app.kubernetes.io/name: ycsb
    app.kubernetes.io/instance: ycsb-sample
    app.kubernetes.io/part-of: kubebench
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubebench
  name: ycsb-mysql
spec:
  target:
    driver: mysql
    host: "mycluster-mysql.default.svc.cluster.local"
    port: 3306
    user: root
    password: "ncqsgzb7"
    database: "mydb"