apiVersion: benchmark.apecloud.io/v1alpha1
kind: Tpch
metadata:
  labels:
    app.kubernetes.io/name: tpch
    app.kubernetes.io/instance: tpch-sample
    app.kubernetes.io/part-of: kubebench
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubebench
  name: tpch-sample
spec:
  target:
    host: "mycluster-mysql.default.svc.cluster.local"
    port: 3306
    user: root
    password: "ncqsgzb7"
    database: "mydb"