apiVersion: benchmark.apecloud.io/v1alpha1
kind: Ycsb
metadata:
  labels:
    app.kubernetes.io/name: ycsb
    app.kubernetes.io/instance: ycsb-sample
    app.kubernetes.io/part-of: kubebench
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubebench
  name: ycsb-sample
spec:
  # TODO(user): Add fields here
