apiVersion: benchmark.apecloud.io/v1alpha1
kind: Tpcc
metadata:
  labels:
    app.kubernetes.io/name: tpcc
    app.kubernetes.io/instance: tpcc-sample
    app.kubernetes.io/part-of: kubebench
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubebench
  name: tpcc-sample
spec:
  # TODO(user): Add fields here
