# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/benchmark.apecloud.io_sysbenches.yaml
- bases/benchmark.apecloud.io_pgbenches.yaml
- bases/benchmark.apecloud.io_ycsbs.yaml
- bases/benchmark.apecloud.io_tpccs.yaml
- bases/benchmark.apecloud.io_tpches.yaml
- bases/benchmark.apecloud.io_fios.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_sysbenches.yaml
#- patches/webhook_in_pgbenches.yaml
#- patches/webhook_in_ycsbs.yaml
#- patches/webhook_in_tpccs.yaml
#- patches/webhook_in_tpches.yaml
#- patches/webhook_in_fios.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_sysbenches.yaml
#- patches/cainjection_in_pgbenches.yaml
#- patches/cainjection_in_ycsbs.yaml
#- patches/cainjection_in_tpccs.yaml
#- patches/cainjection_in_tpches.yaml
#- patches/cainjection_in_fios.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
