name: Release Chart

on:
  workflow_dispatch:
    inputs:
      chart_version:
        description: 'The version of helm chart'
        required: true
        default: ''
  release:
    types:
      - published

env:
  RELEASE_VERSION: ${{ github.ref_name }}
run-name: Release Chart ${{ inputs.chart_version || github.ref_name }}


jobs:
  release-version:
    runs-on: ubuntu-latest
    outputs:
      release-version: ${{ steps.get_version.outputs.release_version }}
    steps:
      - name: Get Chart Version
        id: get_version
        run: |
          VERSION=${{ inputs.chart_version }}
          if [ -z "$VERSION" ]; then
              VERSION=${{ env.RELEASE_VERSION }}
          fi
          echo release_version=$VERSION >> $GITHUB_OUTPUT

  release-chart:
    needs: release-version
    uses: apecloud/apecloud-cd/.github/workflows/release-charts.yml@v0.1.52
    with:
      MAKE_OPS: "bump-chart-version"
      VERSION: "${{ needs.release-version.outputs.release-version }}"
      CHART_NAME: "kubebench"
      CHART_DIR: "deploy/helm"
      CHECK_ENABLE: false
    secrets: inherit

  release-message:
    runs-on: ubuntu-latest
    needs: [ release-chart ]
    outputs:
      content-result: ${{ steps.release_message.outputs.content_result }}
    if: ${{ always() && github.event.action == 'published' }}
    steps:
      - uses: actions/checkout@v6
      - name: release message
        id: release_message
        run: |
          CONTENT="error"
          if [[ "${{ needs.release-chart.result }}" == "success" ]]; then
              CONTENT="success"
          fi
          echo 'content_result='$CONTENT >> $GITHUB_OUTPUT

  send-message:
    needs: [ release-version, release-message ]
    if: ${{ always() && github.event.action == 'published' }}
    uses: apecloud/apecloud-cd/.github/workflows/feishui-message.yml@v0.1.55
    with:
      TYPE: "2"
      CONTENT: "release kubebench chart ${{ needs.release-version.outputs.release-version }} ${{ needs.release-message.outputs.content-result }}"
      APECD_REF: "v0.1.55"
    secrets: inherit
